<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <material name="red">
        <color rgba="0.8 0 0 1" />
    </material>

    <material name="gray">
        <color rgba="0.7 0.7 0.7 1" />
    </material>

    <material name="green">
        <color rgba="0 0.8 0 1" />
    </material>

    <material name="blue">
        <color rgba="0 0 0.8 1" />
    </material>

    <xacro:property name="body_length" value="0.2" />
    <xacro:property name="body_width" value="0.15" />
    <xacro:property name="body_height" value="0.065" />
    <xacro:property name="body_mass" value="1.150" />

    <xacro:property name="lidar_radius" value="0.05" />
    <xacro:property name="lidar_length" value="0.06" />
    <xacro:property name="lidar_mass" value="0.19" />

    <xacro:property name="lidar_stand_length" value="${lidar_radius * 2}" />
    <xacro:property name="lidar_stand_width" value="${body_width * 0.75}" />
    <xacro:property name="lidar_stand_height" value="0.09" />
    <xacro:property name="lidar_stand_mass" value="0.100" />

    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_length" value="0.026" />
    <xacro:property name="wheel_mass" value="0.032" />

    <xacro:property name="caster_radius" value="0.02" />
    <xacro:property name="caster_mass" value="0.03" />

    <xacro:property name="holder_radius" value="0.01" />
    <xacro:property name="holder_length" value="0.15" />
    <xacro:property name="holder_mass" value="0.1" />

    <xacro:property name="tray_length" value="${body_length * 0.9}" />
    <xacro:property name="tray_width" value="${body_width * 0.9}" />
    <xacro:property name="tray_height" value="0.02" />
    <xacro:property name="tray_mass" value="0.1" />
</robot>